# Generated by Django 3.1 on 2020-08-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='alias',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
